### ISSUE TITLE
are you able to add a function to get all the online classes (bbb)?

### ISSUE THREAD

**Issue by YakirOren** [Xiddoc/MashovAPI#1]

**Comment by Xiddoc** [comment]
I haven't worked on this project in a while but I'll try to add one asap.

**Comment by TheOnion313** [comment]
Hi There @YakirOren,
I am an associate of @Xiddoc 
can I add u to our telegram group chat to discuss?

if so please send your telegram handle so we can add you

**Comment by Xiddoc** [comment]
My school doesn't use Mashov anymore, we use Teams, so I can't resolve the API endpoint and parameters needed. If you want to help me add this to the API, contact me so I can look into it.

**Comment by YakirOren** [comment]
add me on discord YakirOren#1424

**Comment by Xiddoc** [comment]
👌
